- machine_test.go
Fixes #25
Better error message
> test: Better error message for missing vsock perms

- machine_test.go
Fixes https://github.com/firecracker-microvm/firecracker-go-sdk/issues/29
Better error message
> test: Error message for missing vsock support

- command_builder.go
- doc.go
- firecracker.go
- machine.go
- opts.go
godoc: add new and enhance existing documentation
> godoc: add new and enhance existing documentation

- README.md
> readme: add build status badge

- .buildkite/pipeline.yml
- HACKING.md
- command_builder.go
- command_builder_test.go
- example_test.go
- fctesting/utils.go
- handlers.go
- handlers_test.go
- jailer.go
- jailer_test.go
- machine.go
- machine_test.go
- pointer_helpers.go
This adds support for jailer... again due to messing up of the commit history. 
> adding support for jailer

- .buildkite/pipeline.yml
> Adding support for testing against v0.15.0 firecracker

- CHANGELOG.md
> Adding CHANGELOG file

- README.md
> readme: Scope build badge to the master branch

- README.md
Signed-off-by: Noah Meyerhans <nmeyerha@amazon.com>
Update README.md to include "questions" section, including details on reporting security issues.
> Update README to include contact info

- machine_test.go
> Adding tests for PID method

- jailer.go
- jailer_test.go
This change also includes a fix where NetNS was not being set as
expected. It's bundled here because the updated unit tests would
not pass without it.
Signed-off-by: Erik Sipsma <sipsma@amazon.com>
Closes #106 
> Support providing a different jailer binary.

- example_test.go
Previous jailer example led to some confusion, #92, due to not knowing the need to manually set up the proper jailer workspace. New example uses the jailer config in which allows the SDK to do all the setting up.
> Updating jailer example to use the jailer config

- CHANGELOG.md
> Update to version v0.17.0

- .buildkite/pipeline.yml
- HACKING.md
NA
Instead of moving things to pipeline.yml, this change explains more
about the EC2 instance we are using.
> Document about the environment where we run all tests

- cni/cmd/tc-redirect-tap/main.go
- cni/cmd/tc-redirect-tap/main_test.go
- cni/internal/cniutil.go
- cni/internal/cniutil_test.go
- cni/internal/mocks.go
- cni/internal/netlink.go
- cni/vmconf/vmconf.go
- cni/vmconf/vmconf_test.go
- go.mod
- go.sum
Signed-off-by: Erik Sipsma <sipsma@amazon.com>
There are unit tests and have also verified with e2e tests that will be included in upcoming GoSDK+Firecracker-containerd PRs (which are too large to include with this change).
> Add DEL and CHECK support to tc-redirect plugin

- drives.go
- drives_test.go
NA
This would make https://github.com/firecracker-microvm/firecracker-containerd/pull/283 cleaner.
> Define functional options for DrivesBuilder

- Makefile
NA
The testdata/ directory must have vmlinux, root-drive.img and firecracker
binary, in order to run Go tests.
This change prepares the files by just running "make".
> Prepare files under testdata/ from Makefile

- README.md
Fixed a typo on CNI network configuration example.
> typo in cni network config

- cni/cmd/tc-redirect-tap/args/args.go
- cni/cmd/tc-redirect-tap/main.go
- cni/cmd/tc-redirect-tap/main_test.go
Signed-off-by: bpopovschi <zyqsempai@mail.ru>
*Issue #131 , #132 *
Added possibility to set `tapName`, `tapUID` and `tapGID` from CNI cmd args
Added test for `newPlugin` function
> Added possibility to set tapName, tapUID and tapGID from CNI cmd args

- .buildkite/pipeline.yml
- machine_test.go
- network_test.go
#150.
The default is 1 since #144. Fixes #150.
> Correctly set DISABLE_ROOT_TESTS on the root tests

- .buildkite/pipeline.yml
- drives.go
- machine_test.go
- network_test.go
NA
I'm unsure we need full-fledged golangci-lint here, but gofmt is probably nice to have.
> Run gofmt on BuildKite

- README.md
Signed-off-by: Erik Sipsma <sipsma@amazon.com>
> Document obtaining CNI generated IP address

- README.md
> Add a GoDoc badge

- client/models/boot_source.go
- client/swagger.yaml
- handlers.go
- jailer.go
- machine.go
- machine_test.go
Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
`master` version of `firecracker` adds support for `initrd_path`, this PR adds support to Go SDK
> Update Swagger API spec to include new option, InitrdPath

- .buildkite/pipeline.yml
- go.mod
- go.sum
Since Dependabot doesn't update these files. The failure is treated as
a "soft" failure.
https://github.com/dependabot/feedback/issues/215
> Check go.mod and go.sum on BuildKite

- CHANGELOG.md
- version.go
> Release 0.21.0

- handlers.go
NA
I'm not so sure why we wanted to treat that as a warning.
> Make setupLogging's error as an error

- machine_test.go
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
This fixes a dropped test error.
> firecracker: fix dropped test error

- benchmark_test.go
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
From go doc: `testing.B.Fatal()`: "Fatal is equivalent to Log followed by FailNow."
More from `go doc testing.B.FailNow()`:
>  FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test. Calling FailNow does not stop those other goroutines.
This ought fix the benchmark tests to not attempt `b.Fatal()` inside a goroutine.
> Fix Benchmark Goroutine

- .buildkite/pipeline.yml
- go.sum
> go mod tidy

- .buildkite/hooks/pre-checkout
> Remove root-owned files

- Makefile
- README.md
- client/models/balloon.go
- client/models/balloon_stats.go
- client/models/balloon_update.go
- client/models/drive.go
- client/swagger.yaml
To fix #340: Outdated Slack link
> Update slack link on README.md

- Makefile
- README.md
- client/models/balloon.go
- client/models/balloon_stats.go
- client/models/balloon_update.go
- client/models/drive.go
- client/swagger.yaml
This reverts commit 647aa41da18a24a8e097183c4d86fd680324d559. Because the commit includes two changes:update slack url + update yaml that should commit separately. 
> Revert "Fix #340 Update slack link on README.md (#341)"

- README.md
To fix #340: Outdated Slack link
> Fix #340 Update slack link on README.md

- vsock/dial.go
- vsock/listener.go
This commit refactors vsock package's methods more like other
Go packages such as net.Dialer and grpc.ClientConn.
https://pkg.go.dev/net#Dialer
https://pkg.go.dev/google.golang.org/grpc#ClientConn
> Define vsock.Dial and vsock.DialContext as like net and grpc

- .gitignore
N/A
Expand the .gitignore to include some build artifacts generated during build and test.
> chore: ignore build artifacts

- machine.go
N/A
Minor change to remove dead code from machine method(s).
Fixes one linter warning from golangci-lint.
> chore: remove dead code from machine

- machine_test.go
Closes #435
Signed-off-by: Mathis Joffre <mariusjoffre@gmail.com>
> Add test for WithSnapshotOpt

- go.mod
- machine.go
- machine_test.go
Closes: #428
*Description of changes:* add a cleanup chan to ensure cleanup is waited by the stopVMM method.
Signed-off-by: Sugate <mariusjoffre@gmail.com>
> Wait for cleanup to be done after stop VMM

- .github/workflows/go.yml
> Add support for go 1.18, 1.19

- machine.go
N/A
The statement `<-ctx.Done()` without a `select {}` wrapping it will cause a goroutine leak if `ctx` is `context.Background()` or `context.TODO()` (or any other context that doesn't get cancelled, intentionally or not).
This change allows the goroutine to exit if the VM exits on its own, in addition to waiting for `ctx.Done()`, preventing a goroutine leak in case people do pass in a context that doesn't get canceled, but are otherwise managing the VM lifecycle correctly.
---
> Fix goroutine leak in startVMM

- .github/dependabot.yml
> update dependabot to run gomodinside examples/cmd/snapshotting

- examples/cmd/snapshotting/go.mod
- examples/cmd/snapshotting/go.sum
Need to update containernetworking/plugins version after #566 
> run go mod tidy in examples/cmd/snapshotting

- go.mod
- go.sum
> fix: upgrade golang.org/x/net v0.33.0

- machine.go
> fix: check logger nil after applying opts

- examples/cmd/snapshotting/go.mod
- examples/cmd/snapshotting/go.sum
This change is from running go mod tidy after #632 merged.
> Fix examples go mod
