- cmd/firectl/main.go
- firecracker.go
- machine.go
- machine_test.go
This allows to see HTTP requests/responses logs from/to Firecracker in debug mode. 
> Trace HTTP requests to Firecracker in debug mode

- HACKING.md
- Makefile
- client/models/error.go
- client/operations/operations_client.go
- client/operations/put_mmds_responses.go
- client/swagger.yaml
- cmd/firectl/main.go
- firecracker.go
- machine.go
- machine_mock_test.go
- machine_test.go
*Issue #:* #12
* Adding metadata support in the api & cli
* Added allow mmds to network card (automatically set to enabled in cli if metadata provided)
* Added a test in machine_test.go and tested manually. made sure test pass with `make test`
* Added `make generate` target for convenience and update HACKING.md
> Add Metadata support

- README.md
- cmd/firectl/README.md
Move the firectl documentation to a dedicated README and clean up the example.
> Move most of the firectl docs to a dedicated README

- swagger.go
Email validation has a network dependency.  We do not want to enforce
that the container has a working network when generating the swagger
dependencies.
> swagger: disable validation

- machine_test.go
Fixes #26 
* Use `panic=0` kernel cmdline option
* Stat the vmlinux file to give a better error message when it's missing
> Disable reboot-on-panic, validate that kernel file is present

- cmd/firectl/main_test.go
- machine_test.go
TestStartVMM was leaking a process due to not having proper cleanup when
tests have completed.
Fixes #33 
> ensure tests have stopped VM upon completion

- HACKING.md
- machine.go
- machine_test.go
Fixes https://github.com/firecracker-microvm/firecracker-go-sdk/issues/37
* Check for nil Process before calling Signal
* Use a different channel for signaling the end of TestMicroVMExecution when startVMM fails
* Skip waiting for stabilization if the VMM isn't running
* Update HACKING.md
> machine: StopVMM should not panic on nil Process 

- cmd/firectl/main.go
- example_test.go
- handlers.go
- handlers_test.go
- machine.go
- machine_test.go
- pointer_helpers.go
`LogFifo` and `MetricsFifo` can now log its contents to a file by setting the `FifoLogWriter` which is an `io.Writer` to handle the fifo streams content.
Some refactors here on how the `Machine` object flows through its instructions. Previously these instructions were all called during the initialization phase. However, to make the `Machine` more flexible and extendable, this introduces handler lists which is a command pattern queue. `Init` is no longer needed, as that is now handled through `Handlers`.
> adding fifo logging files and refactoring the SDK

- drives.go
- drives_test.go
- example_test.go
- pointer_helpers.go
Adds a drives builder to help users with building a series of drives
without needing to know the intricate details of firecracker's API.
> Adding drives builder

- Makefile
- machine_test.go
This change makes modification to separate out integration tests from
unit tests. This makes it a little nicer to run only unit tests when
developing and finally running integration as a last check.
> seperating out integration tests from unit tests

- client/client_transports_test.go
Fixing test bug with hanging requests
Prior tests caused the HTTP client to hang waiting for a response. This
will now properly write a response and closing the request.
Fixes #52
> client: fixing test bug with hanging requests

- machine.go
- machine_test.go
Prior to this change, multiple calls to `Wait()` could result in the error being lost, and for subsequent callers to wait until their context was canceled rather than waiting for the VMM to exit.  This change makes it such that multiple callers of `Wait()` will all block for the VMM exit (or their individual context cancellation) and will receive the same error (for non-canceled contexts).
This behavior was causing `TestMicroVMExecution` to take 30 seconds every time, which was the length of the `vmmCtx` timeout.  After this change, `TestMicroVMExecution` takes ~7 seconds, which is the length of the calls to `time.Sleep` in that test.
The other commits in this pull request are either in support of making `Wait()` safe (like enforcing that `Start()` can only be …
> Make machine.Wait() safe for multiple calls

- example_test.go
- machine.go
- rate_limiter.go
- rate_limiter_test.go
Adds support for rate limiting for inbound and outbound data streams of
firecracker. This also introduces a TokenBuilder which can be passed
into the NewRateLimiter factory function to return a new rate limiter.
> add support for rate limiting

- example_test.go
- machine.go
Example names were not Go idiomatic along with some Machine method
copying locks which vet was complaining about.
> Fixes vetting issues

- client_transports.go
- client_transports_test.go
- firecracker.go
Moves client/client_transports.go and client/client_transports_test.go
to the firecracker package due to generation deleting everything in the
client directory
> client: moves transport files to firecracker package

- firecracker.go
- machine.go
- machine_test.go
Introduces a new method on `Machine` called `UpdateGuestDrive`, which will allow patching a given guest drive's path. If firecracker ever adds additional fields that can be patched, the `PatchGuestDriveByIDOpt` can be used to set the newly introduced fields.
Fixes #39 
> Adding support for patch guest drive

- machine.go
*Issue #, if available:* None
*Description of changes:* The field should be named AllowMMDS in the NetworkConfiguration to reflect
the name in Firecracker swagger model.
> fix field name typo AllowMDDS -> AllowMDDS

- .buildkite/pipeline.yml
- HACKING.md
- README.md
- command_builder.go
- command_builder_test.go
- example_test.go
- fctesting/utils.go
- firecracker.go
- handlers.go
- handlers_test.go
- jailer.go
- jailer_test.go
- machine.go
- machine_test.go
- pointer_helpers.go
Adds support for firecracker's jailer. This allows for more secure virtualization through creation of namespaces and cgroups. Jailer can be turned on by setting the `EnableJailer` flag. This also implements a very naive mapper and issue #56 is to implement a smarter mapper.
`go test` requires sudo since jailer requires sudo...
Fixes #11
> adding support for jailer

- .buildkite/pipeline.yml
https://github.com/firecracker-microvm/firecracker-go-sdk/issues/73
tap removal now completes regardless of whether the tests fail
> .buildkite: clean up taps after test failure

- handlers.go
121ef9ac introduced Firecracker MMDS support, but included a bug that prevented
it from actually setting the given MMDS value.
Signed-off-by: Noah Meyerhans <nmeyerha@amazon.com>
*Issue #77 
Fix the coding error described in #77. Fix can be confirmed using the same firectl command line as shown in that issue:
```
$ ./firectl --kernel ~/bin/vmlinux --root-drive ~/src/firecracker/images/rootfs.img \
-d --metadata='{"my_key":"xyz"}' --tap-device=fc-test-tap0/6a:11:48:21:1a:d5
...
DEBU[0000] Running handler fcinit.SetMetadata           
DEBU[0000] PUT /mmds HTTP/1.1
Host: localhost
User-Agent: Go-http-client/1.1
Content-Length: 17
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip
{"my_key":"xyz"}
DEBU[0000] HTTP/1.1 204 No Content
Content-Length: 0
Date: Thu, 28 …
```
> Fix coding error in NewSetMetadataHandler

- machine.go
- machine_test.go
#72 added firecracker 0.15.0 API support to the generated client. This change introduces a machine.Shutdown() method to wrap that generated API.
It also includes some improvements to tests to help with consistency and debuggability.
> Wrap the CtrlAltDel API in a machine.Shutdown() method

- CHANGELOG.md
- version.go
Signed-off-by: Noah Meyerhans <nmeyerha@amazon.com>
As discussed in firecracker-microvm/firectl#24, the SDK did not include a wrapper for the `SendCtrlAltDel` Firecracker API with the 0.15.0 release. We've since added support for that API in #81 as the `machine.Shutdown()` method and should release a 0.15.1 version of the SDK including this change.
This PR prepares for that release by updating the changelog.
> Update changelog for 0.15.1 release

- CHANGELOG.md
- machine.go
- machine_test.go
Due to using an empty value, this would cause Firecracker to use their
default socket path which is /tmp/firecracker.socket. This change uses
the config that actually has the socket path value
> Fixes bug where default socket path would be used

- machine.go
- machine_test.go
- Don't create logger instance inside `NewMachine` if using `WithLogger` option (as it'll be overridden)
- `exitCh` wasn't closed under certain conditions
- ~Added public `ExitCh` to track VM exit outside SDK~
> A few minor fixes in SDK

- jailer.go
This allows setting Stdout and Stderr in the JailerCfg without using NewJailerCommandBuilder
> Allow setting stdout and stderr with a JailerCfg

- .buildkite/pipeline.yml
- CHANGELOG.md
- jailer.go
- jailer_test.go
- machine.go
> Updating jailer to be compatible with v0.16.0

- swagger.go
The goswagger API client generator tries to access github.com repeatedly when
running. We're running with no network at all, so these requests are currently
timing out. (Why aren't they getting ENETUNREACH or similar?) This change adds
an entry to /etc/hosts in the container where we run goswagger to point
github.com at localhost, which results in a fast failure and significantly
reduces the time needed to generate the API client code.
For comparison, without this change:
```
$ git checkout master && time make generate
...
make generate  0.44s user 0.25s system 0% cpu 22:34.21 total
$ git checkout api-client-generator-really-really-has-no-network-and-i-mean-it && time make generate
...
make generate  0.40s user 0.24s system 4% cpu 14.327 total
```
22:34 versus 00:14.
Signed-off-by: Noah …
> Fix goswagger network timeouts during client generation

- .gitignore
- CHANGELOG.md
- handlers.go
- jailer.go
- jailer_test.go
- machine.go
- machine_test.go
- Adds configurable Stdin on jailer
- Proper handling of the logs and metrics fifos
- Adds `machine.PID()` to get the process ID and possibly gather metrics on the process
> Improves and fixes jailer

- machine.go
Access to the microvm's process PID is useful for getting process metrics as well as keeping state around. We're using scheduling software and knowing about the PID allows us to "reattach" the task.
> Expose machine's PID

- firecracker.go
- machine.go
- machine_test.go
- machineiface.go
#66
While both Drive and NetworkInterface can have RateLimiters on creation,
updating RateLimiters is only supported by NetworkInterface
(via PartialNetworkInterface).
> Add UpdateGuestNetworkInterface

- fctesting/utils.go
- firecracker_test.go
- handlers_test.go
- machine.go
- machine_test.go
N/A
It makes `go test` less noisy and helps us to find the usage of
the global default logger. Since Machine and Client take logrus.Entry,
they shouldn't use the default one.
> Make logrus' log level configurable via FC_TEST_LOG_LEVEL

- machine.go
It should fix signal handlers, now after even after instances have been started before on [unik](https://github.com/solo-io/unik), it's possible to close it with CTRL+C.
I have tested it on older versions of this library used by unik.
> machine: stop signal listener

- example_test.go
- handlers.go
- jailer.go
- jailer_test.go
- machine.go
- machine_test.go
This fix allows for a more intuitive design in letting users enable the
jailer.
> Removes JailerEnable and changes JailerCfg to be a pointer

- handlers.go
- jailer.go
- machine.go
- machine_test.go
Exposing the config allows for modification of the machine configuration
during the 'Start' method. An example usage of this is using a custom
jailer
Also fixes a linting issue for `ErrMissingJailerConfig`
> Expose config to allow for advanced handlers

- handlers.go
- handlers_test.go
Prepend will allow for prepending to a given handler list adding
flexbility  to the handler list.
> Adding Prepend to HanderList

- machine.go
A colleague of mine (@garslo) found there was a ticker not being closed in waiting for a socket during VM start. We observed considerable CPU usage when 20+ Firecracker VMs were spun up on a single system.
> Fixed ticker leak in waitForSocket when starting a VM

- .buildkite/pipeline.yml
- client/models/vsock.go
- client/operations/operations_client.go
- client/operations/put_guest_vsock_by_id_responses.go
- client/swagger.yaml
- fctesting/firecracker_mock_client.go
- firecracker.go
- handlers_test.go
- machine.go
- machine_test.go
#121 
- Updates swagger.yml and regenerates client and client operations.
- Manual changes to swagger.yml to reflect reality of 0.18 (just `id => vsock_id`)
- Adapt non-generated code to use the new APIs
- Sets the vsock device index as its ID (instead of a name based on the path)
- Is not backwards compatible with 0.17 (at least, I don't think so)
> support 0.18's new vsock API

- network_test.go
Some of the tests in this package are expected to run as root in order
to perform privileged operations.  These tests may also create files,
but if they do so without setting the w bit for the other group, the
files will not be deletable after the test by a normal user.  This
commit sets the writable bit on the file permissions only so that the
files can be deleted by non-root users after the tests complete.
https://github.com/firecracker-microvm/firecracker-go-sdk/pull/134
> network: set broad permissions

- .gitignore
- handlers.go
- handlers_test.go
- machine.go
Carries https://github.com/firecracker-microvm/firecracker-go-sdk/pull/134
fifos for Firecracker logs and metrics are now created and queued for cleanup in CreateLogFilesHandler.  This removes warnings when using the jailer and setting other paths for the fifos.
Fixes: https://github.com/firecracker-microvm/firecracker-go-sdk/issues/133
Original contribution: https://github.com/firecracker-microvm/firecracker-go-sdk/pull/134
> handlers: moved fifo setup/cleanup to handler

- fctesting/test_writer.go
- handlers_test.go
- machine.go
- machine_test.go
Prior to this fix the FifoLogWriter would hang the process due to
waiting for the fifo to be connected to firecracker when attempting to
open the fifo. This fix wraps the capture fifo method in a goroutine.
Fixes #143 
> Fixes issue where FifoLogWriter would hang

- handlers.go
- machine.go
- machine_test.go
This change fixes a leak that occurs when using context cancel or
stopping the VM. The goroutine in `captureFifoToFile` spins up a
goroutine to copy the contents of the file, but will continue reading
from the file even if the VM shuts down. To prevent this, we now look at
the context to see if it has finished or if the machine has closed its
exit channel
Fixes #146 
> Fixes leak of open file during capture fifo

- machine.go
- machine_test.go
- network_test.go
NA
`err` was actually the variable outside of the goroutine.
> Report its exit status from Wait() correctly

- README.md
The "ptp" plugin's "ipMasq: true" setting is, in practice, very inconsistent in
actually setting up networking from the veth device to host networks. The
firewall plugin has been much more consistent, so including it as the example
configuration results in a better default experience for users trying out CNI
support.
Signed-off-by: Erik Sipsma <sipsma@amazon.com>
> Include the firewall CNI plugin in sample configuration.

- go.mod
- go.sum
- handlers.go
- machine.go
- machine_test.go
This fix adds a retry around io.Copy to retry the fifo until it is
connected on the other end. Prior to this fix, the io.Copy would
immediately exit without error.
Fixes #156 
> Fixes race with io.Copy and O_NONBLOCK file

- version.go
This releases v0.19.0, which includes support for network configuration via CNI and firecracker's new vsock implementation.
> Bump version to 0.19.0

- .buildkite/pipeline.yml
- machine.go
- machine_test.go
- network_test.go
#157
Seems Go's race detector can detect the leak issue (while I haven't tested @xibz's fix yet) and no false positives. Can we enable the detector on BuildKite?
> Enable Go's race detector

- jailer.go
- jailer_test.go
- machine.go
This change moves the NetNS field from the JailerConfig to the Config.
This makes the most sense since net namespaces are not subject to only
jailers, but can be used generally as well.
> Moves NetNS to Config from JailerConfig 

- cni/cmd/tc-redirect-tap/args/args.go
- cni/cmd/tc-redirect-tap/main.go
s/TCRedirectTapGUID/TCRedirectTapGID/g
> Fixes typo for args.TCRedirectTapGID

- HACKING.md
- firecracker.go
- machine.go
- utils.go
- utils_test.go
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>
Issue #164 
Added `FIRECRACKER_INIT_TIMEOUT_SECONDS` env to configure init timeouts and `FIRECRACKER_REQUEST_TIMEOUT_MILLISECONDS` for request timeouts.
> Added env's to be able to configure timouts

- machine.go
- machine_test.go
- testdata/sigprint.sh
*Issue #, if available:* #85 
Adds a `DisableSignals` option to `machine.Config` for host apps that need to manage firecracker signals themselves. This also fixes an issue where signals weren't cleaned if the firecracker socket failed to open.
> Configurable signal handling, fix signal cleanup

- machine_test.go
As like other tests, keeping the socket under testadata/ allows us to
run multiple builds (e.g. master and PRs) in parallel on a same host.
> Keep a socket file under testdata/

- .buildkite/pipeline.yml
- CHANGELOG.md
- HACKING.md
- version.go
NA
Seems Firecracker 0.20.0 doesn't have any API changes, but we have a few fixes on our client code and keeping the versions in-sync may help customers.
> Release 0.20.0

- machine.go
NA
If there's no root disk in the config, validation fails while trying to
stat path `""`.
> Relax validation for configuration without root disk device

- .buildkite/pipeline.yml
- machine_test.go
This commit adds the FC_TEST_JAILER_BIN which allows user to specify
which jailer binary to use during testing.
> Adds FC_TEST_JAILER_BIN to specify test jailer bin

- .buildkite/pipeline.yml
- .gitignore
- Makefile
- machine_test.go
- tools/docker/Dockerfile
- tools/docker/entrypoint.sh
This change adds a test step in BuildKite to test against HEAD of
Firecracker. The test will utilize Docker to run against Firecracker's
master branch.
> Add test step to test against HEAD of Firecracker

- fctesting/utils.go
- fctesting/utils_test.go
This would panic due to not setting up default arguments such as the
Formatter in the logger when using the FC_TEST_LOG_LEVEL. This fix
instead uses log.New() to have the necessary bootstrapping occur and
sets the necessary fields as needed.
> Fixes panic due to struct initiliaztion

- cni/vmconf/vmconf.go
- cni/vmconf/vmconf_test.go
- network.go
- network_test.go
#173
This allows passing `ip=` kernel configuration to the VM with interface
name set. In our case, kernel has bonding support enabled, so `bond0`
interface exists on boot, and it will be picked up for kernel
configuration unless `eth0` is specified explicitly in the configuration
line.
Change is backwards compatible, as interface name defaults to empty
string.
Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
> Allow passing VM interface name with CNI configuration

- network.go
- network_test.go
N/A
This allows for more smooth automated firecracker VM provisioning with
CNI: automation doesn't need to write any files to user's CNI conf dir
in case network config is auto-generated (not supplied by the user).
Either `NetworkName` or `NetworkConfig` are required, change is fully
backwards compatible.
Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
> Allow parsed CNI config to be passed in

- Makefile
- tools/docker/entrypoint.sh
NA
firecracker-containerd sometimes cannot build Firecracker, probably due to the fact that Go SDK uses "cargocache" volume as root.
While we can change the run-as user to make both of them compatible, I'd like to rather getting rid of dependencies between 2 projects.
> Rename "cargocache" volume since firecracker-containerd is using the same volume

- machine.go
- machine_test.go
The method should guarantee that the underlying process is dead,
but it didn't.
> Make sure Machine#Wait() gurantee that the underlying Firecracker process is stopped

- .gitignore
- Makefile
- tools/docker/Dockerfile
- tools/docker/entrypoint.sh
NA
entrypoint.sh assumes that the parameters are for "cargo build ...",
which doesn't work with firecracker-clean target.
Instead of fixing the shell script, this change makes the container
itself more neutral by accepting any arbitrary commands.
> Fix firecracker-clean target

- network_test.go
NA, but master build is failing due to this test.
This test is sending ICMP pings to microVMs.
However since Machine#Start() only *starts* a microVM and not aware
about the status of the guest OS, some packets are sent while the OS is
booting.
> Don't count pings while a guest OS is booting 

- .buildkite/hooks/pre-exit
- .buildkite/pipeline.yml
- .gitignore
- jailer.go
- jailer_test.go
- machine.go
- machine_test.go
Firecracker has since removed specifying the seccomp level in the jailer
and now is specified in Firecracker instead. This change removes the
seccomp level from the jailer and adds it to machine instead.
TODO:
#175 
> Remove SeccompLevel from Jailer

- machine.go
- machine_test.go
*Issue #, if available:* https://github.com/firecracker-microvm/firecracker-go-sdk/issues/200
1. Turn `TestWait/StopVMM_+_Context_Cancel` into a failing test case: after the VM is terminated (via exit(0) or signal) and context is cancelled, an error is logged.
1. Patch `machine.stopVMM()` to not send `SIGTERM` if we've already seen the process has exited.
> stopVMM: don't signal if stopped

- go.sum
Version upgrade forgot to `go mod tidy`
> Running go mod tidy to remove old testify version

- benchmark_test.go
- machine.go
#198 
The first commit is a benchmark to reproduce the issue. The second commit is actually fixing the issue. We are not removing signal handling channels (sigchan in setupSignals).
> Remove signal handling channels correctly

- go.mod
- go.sum
- machine_test.go
NA
This test is occasionally failing on my host. Seems there is a timing
issue.
containerd/fifo upgrade is required to use fifo.ErrReadClosed.
The error was not exported before.
> Fix a timing issue on TestCaptureFifoToFile_leak

- .buildkite/pipeline.yml
Due to some wanting to be able to sync with master with a breaking
change, we swapped which tests were failing, from master tests to root
tests. Now that we've merged in v0.21.0 of Firecracker, root tests
should now pass
> Move soft_fail back to master tests

- Makefile
NA
These rules were added to easily start developing the SDK, but it
hasn't been updated since 0.18.0.
> Download Firecracker 0.21.1 and its jailer from Makefile

- cni/cmd/tc-redirect-tap/main_test.go
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
This fixes a dropped `err` variable in the tests for `cni/cmd/tc-redirect-tap`.
> cni/cmd/tc-redirect-tap: fix dropped test error

- .buildkite/pipeline.yml
- go.mod
- go.sum
Buildkite is running into permission issue while trying to override the
firecracker and jailer binaries in the testdata folder. Also creates the
testdata/bin folder which was failing due to not existing.
> Fixing buildkite failure

- jailer.go
- jailer_test.go
- machine_test.go
Signed-off-by: Jerome Gravel-Niquet <jeromegn@gmail.com>
> machine config is not available at this time

- machine.go
Example with firectl:
```
$ ./firectl --kernel=./vmlinux
WARN[0000] Failed handler "validate.Cfg": failed to stat host path, "": stat : no such file or directory
FATA[0000] Failed to start machine: failed to stat host path, "": stat : no such file or directory
```
As you can see it's rather impossible for the user to tell what exactly is missing.
> Clarify error message when host drive path is inaccessible

- tools/docker/Dockerfile
NA
Firecracker uses 1.43.1 since
https://github.com/firecracker-microvm/firecracker/commit/2397f6a24041870c7fa7d41b0715a5aa8e2f97db.
> Upgrade Rust from 1.39 to 1.43.1

- machine_test.go
This logs and handles two dropped test errors in the `firecracker` package.
> firecracker: fix dropped test errors

- .buildkite/pipeline.yml
Our BuildKite host now has Go 1.13 in /usr/lib/go-1.13,
Debian's default location.
NA, but master is now broken since we've changed the BuildKite host internally.
See the commit message above.
> Use Go 1.13 in /usr/lib/go-1.13

- jailer_test.go
- machine.go
- machine_test.go
Firecracker is internally has an instance ID, but the SDK didn't have
the way to configure the ID. This change connects Config.VMID to the
instance ID.
NA
* Connects Config.VMID to Firecracker's Instance ID.
* Alternatively we can add Config.InstanceID but I think that would be too confusing.
* Renaming VMID to InstanceID is another option and has less impedance mismatch, but I don't want to break existing customers, including firecracker-containerd.
> Use Config.VMID as Firecracker's instance ID

- Makefile
Since https://github.com/firecracker-microvm/firecracker/pull/2125,
`cargo build` doesn't build jailer by default.
> Build firecracker and jailer explictly

- machine.go
- machine_test.go
This may not have an real use-case, but Firecracker supports
the combination.
NA
Setting a logger without its level possible by converting "" to nil, since it's string's zero value.
> Setting a logger without its level

- README.md
Fixes https://github.com/firecracker-microvm/firecracker-go-sdk/issues/283
Firecracker moved their security policy document to SECURITY.md so that GitHub would recognize the project security policy automatically.  See https://github.com/firecracker-microvm/firecracker/commit/ce1ee597c10026d753a39454b79dfe17d26d20f9.
> readme: fix broken security link

- .github/workflows/go.yml
While GitHub Actions cannot run all tests, it would be nice to have
that to make sure the SDK works on multiple different Go versions.
> Use GitHub Actions

- go.mod
- go.sum
This reverts commit 2e2eaaa3f5b4c1b5903dd792ac774a84a1544ef7 to make
this SDK Go 1.11 compatible.
Debian buster's Go is 1.11, while buster-backports has 1.14. We don't have
strong reasons to drop Go 1.11.
> Revert "Bump github.com/go-openapi/validate from 0.19.12 to 0.19.14"

- handlers.go
- jailer.go
The way `InitrdPath` was implemented is buggy:
- When you set a `initrd_path` with firecracker, [you do not want a root drive](https://github.com/firecracker-microvm/firecracker/issues/186#issuecomment-725957979).
- There was a type (I believe that's what it was) which prevented `initrdFilename` to ever be set to anything other than `""`. This would make the config for `InitrdPath` useless.
With both these changes, I was able to use `initrd_path` successfully.
> Fix InitrdPath usage

- firecracker.go
- go.sum
- handlers.go
- handlers_test.go
- machine.go
The goal of this PR is to support the configuration of MMDS in the SDK.
- Add a handler to call `mmds/config` in handlers.go.
- Add a wrapper to call `mmds/config` in firecracker.go.
- Add a wrapped function call to machine.go.
> Add support for the MMDS configuration.

- .github/dependabot.yml
We've been using Dependabot (dependabot-preview) for upgrading Go
modules. However dependabot-preview has been replaced by the
GitHub-native Dependabot which supports "go mod tidy"!
This change introduces GitHub-native Dependabot by adding its new
configuration file.
https://dependabot.com/docs/config-file/
https://github.blog/changelog/2020-10-19-dependabot-go-mod-tidy-and-vendor-support/
> Use GitHub's native Dependabot to support "go mod tidy"

- Makefile
- machine_test.go
Update the download link for kernel, firecracker and jailer in Makefile to keep consistent with Firecracker team. 
> Update download link for kernel, firecracker and jailer

- .buildkite/pipeline.yml
- .headers/go.txt
- .headers/makefile.txt
- Makefile
- benchmark_test.go
- drives.go
- drives_test.go
- example_test.go
- fctesting/test_writer.go
- fctesting/utils_test.go
- firecracker_test.go
- handlers_test.go
- jailer_test.go
- pointer_helpers.go
- utils.go
- utils_test.go
There are multiple files we forgot to add Amazon's license header.
This change adds a new Makefile targat that check all files to make
sure the header is included.
> Add "lint" target to check Amazon's license header

- .buildkite/pipeline.yml
Since Dependabot is now able to run "go mod tidy", we can make it
mandatory on all changes.
https://github.blog/changelog/2020-10-19-dependabot-go-mod-tidy-and-vendor-support/
NA
Update BuildKite's configuration to make sure "go mod tidy" doesn't modify anything.
> Make go mod tidy mandatory

- machine_test.go
Using t.Fatalf in the goroutine will only exit the goroutine. Use
t.Errorf instead to return failure to the testing function.
> fix use of (*T).Fatalf from non testing goroutine

- firecracker.go
- machine.go
- machine_test.go
This will help use cases where we need to check guest's running state
and other information before taking another action.
Signed-off-by: Alakesh Haloi <alakeshh@amazon.com>
Getting running state of the VM from firecracker is needed many use cases. Implementing DescribeInstance similar to how GetMetadata is implemented.
> Add describeInstance functionality for reading vm info

- .buildkite/pipeline.yml
- .github/workflows/go.yml
- CONTRIBUTING.md
- Makefile
- README.md
We no longer use `master` in the SDK and Firecracker.
> Rename master to main

- Makefile
- client/models/balloon.go
- client/models/balloon_stats.go
- client/models/balloon_update.go
- client/models/drive.go
- client/swagger.yaml
Firecracker v0.24.3 is now released, and we should update our Firecracker as well. This release fix
the balloon API: All "MB" change to "MiB".
This is a patch release introducing the following changes:
· Changed Docker images repository from DockerHub to Amazon ECR.
· Snapshot related host files (vm-state, memory, block backing files) are now flushed to their backing mediums as part of the CreateSnapshot operation.
· ​Fixed ballooning API definition by renaming all fields which mentioned "MB" to use "MiB" instead.
> Update Firecracker from v0.24.2 to v0.24.3

- .github/workflows/go.yml
- Makefile
- fctesting/utils.go
- go.mod
- go.sum
- machine_test.go
While GitHub Actions' environment doesn't have KVM, we can run
a few tests on there to make sure that the SDK works with different
Go versions.
It doesn't run Firecracker, but running some tests is better than
running no tests.
> Run tests on GitHub Actions

- balloon.go
- balloon_test.go
- firecracker.go
- handlers.go
- machine.go
- machine_test.go
Issue #, if available:
Memory ballooning support on firecracker-go-sdk
Description of changes:
Add wrappers for the Firecracker endpoints "/ballloon", "/balloon/statistics" which can be found in [the swagger definition](https://github.com/firecracker-microvm/firecracker/blob/master/src/api_server/swagger/firecracker.yaml).
/ballloon:
GET operations is supported by GetBalloonConfig
PUT operations is supported by CreateBalloon
PATCH operations is supported by UpdateBalloon
/balloon/statistics
GET operations is supported by GetBalloonStats
PATCH operations is supported by UpdateBalloonStats
> Memory ballooning support on firecracker-go-sdk

- .buildkite/pipeline.yml
- The first commit is upgrading Go from 1.13 to 1.15. `go-openapi` needs Go 1.15, which we probably should adopt rather than stop updating. Go 1.15 and Go 1.13 are no longer supported according to https://go.dev/doc/devel/release. We need to discuss #364 later.
- The second commit is making Firecracker's main branch build "soft fail", meaning that the build breakage wouldn't make the whole build broken. Firecracker is making some breaking changes before 1.0. So we cannot make the SDK work with the main branch and released versions.
> Upgrade Go from 1.13 to 1.15

- go.mod
- go.sum
- network_test.go
The package has been moved to github.com/go-ping/ping.
> Migrate from github.com/sparrc/go-ping to github.com/go-ping/ping

- machine_test.go
`github.com/firecracker-microvm/firecracker-go-sdk/client/operations` was being imported twice in `machine_test.go`.
> fix duplicate test imports

- vsock/dial.go
- vsock/dial_test.go
The fix was based on the below PR, but slightly changed to use net.Error
as is.
https://github.com/firecracker-microvm/firecracker-containerd/pull/583
> isTemporaryNetErr didn't work when the error was wrapped

- .buildkite/pipeline.yml
Since 2380785, the SDK should work with Firecracker's main branch.
> Do not soft-fail on Firecracker's main branch build

- jailer.go
- jailer_test.go
Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>
Just allowing to pass `--cgroup-version` to jailer when needed. This is useful to get jailer to work with cgroupv2 while v1 is the default.
> Allow passing cgroup-version to jailer

- client/models/full_vm_configuration.go
- client/swagger.yaml
- firecracker.go
Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>
While working on this I noticed a bug in the swagger.yaml definitions
that were not reflecting the state of the Firecracker API.
Full description https://github.com/firecracker-microvm/firecracker/issues/2963
We probably want to see how the discussion evolves before merging this.
> Add GetExportVMConfig to read the `/vm/config` endpoint

- drives.go
- drives_test.go
Adding a optional function to set "CacheType" of a Drive. "CacheType" is an optional field that we can now set for models.Drive and supports 2 values: "Unsafe" and "Writeback".
The aim is to make use of this function in firecracker-containerd if client requests CacheType to be set for the root drive or the other mounted drives
*Testing:*
make test
> Add a DriveOpt func for configuring CacheType

- cni/internal/cniutil.go
- cni/internal/netlink.go
- cni/vmconf/vmconf.go
- go.mod
- machine.go
- network.go
- vsock/dial.go
- vsock/listener.go
This commit removes the package with the help of
https://github.com/xdg-go/go-rewrap-errors.
fmt.Errorf() can wrap errors nowadays.
> Remove pkg/errors

- firecracker.go
- firecracker_test.go
- machine.go
- machine_test.go
Added the ability for users to get the current version of Firecracker being used, and added tests in both firecracker_test.go and machine_test.go.
Functions were added in where it made some logical sense to me. If it's not consistent with the overall structure please let me know, as I couldn't seem to get the exact structure of the order of the functions in the files. Also, please pay attention to how I tested the function in machine_test.go, as I'm not super confident that's where it should be, but it feels right.
> Added API functionality + testing to get Firecracker Version

- drives.go
- drives_test.go
The Drive model has a variable called `IoEngine` that determines if the block device runs commands synchronously or asynchronously (default synchronous). This PR implements a function to change said variable alongside a test to show that it works.
The default value seems to be nil and I assume that the handling of that is done in Firecracker itself, but if this is not the case, please let me know.
> Added API functionality + testing to change engine IO type

- Makefile
N/A
Cleanup stamp file on firecracker clean so binaries can be re-downloaded again.
> chore: cleanup stamp on firecracker clean

- .buildkite/hooks/pre-exit
- .buildkite/pipeline.yml
- .gitignore
- Makefile
- firecracker.go
- go.mod
- go.sum
- handlers.go
- machine.go
- machine_test.go
- machineiface.go
- opts.go
- snapshot.go
Signed-off-by: David Son <davbson@amazon.com>
Taking most of the code from #348 and modifying it a bit, I was able to implement the ability to load snapshots as an option within the `Start` function in `machine.go` via `WithSnapshot`. This fixes the issue addressed in #348, where `machine.go` exposing `LoadSnapshot` function in said PR was deemed suboptimal due to its guaranteed failure outside of the scope of `Start`.
The actual implemention in `opts.go` initially felt a bit messy, as I felt the extra added imports made it clunky, but @austinvazquez and I looked over it today and decided it was fine given that it ultimately did similar things compared to other options, but feel free to disagree below if you feel otherwise.
By submitting this pull request, I confirm that my contribution …
> Implemented snapshot loading capabilities

- .buildkite/pipeline.yml
Signed-off-by: David Son <davbson@amazon.com>
Added concurrency test to install step in the BuildKite pipeline to reduce/remove flakiness in testing.
The flakiness seems to be due to an issue on Firecracker's end, so if that issue is resolved, this PR can be reverted.
> Add concurrency test to install step in pipeline

- CONTRIBUTING.md
Signed-off-by: Gavin Inglis <giinglis@amazon.com>
n/a
Add a section describing DCO / commit signing, exactly the same info as
we already have on firectl repo to keep things consistent.
I noticed that we are missing some info on commit signing on this project, whereas on firectl and firecracker-containerd we have info on how/why to sign commits. This change adopts the same wording as firectl: https://github.com/firecracker-microvm/firectl/blob/main/CONTRIBUTING.md
> add DCO section for signing commits

- docs/snapshotting.md
- examples/cmd/snapshotting/example_demo.go
- examples/cmd/snapshotting/go.mod
- machine.go
- machine_test.go
- machineiface.go
- opts.go
Signed-off-by: David Son <davbson@amazon.com>
Firecracker can only start a VM once per instance. Because of this, it made sense to me to keep all configuration changes to the `NewMachine` call instead of the `Start` call, as `Start` should simply do that — start the VM. Everything should be in place when the machine starts, so there should be no reason to have an option in said call.
As a result of these changes, `WithSnapshot` is now an option used in `NewMachine`. This also required me to refactor the machine options, putting the options changes at the end of the `NewMachine` call, as putting it where it originally was would not allow me to change the config. This should also allow for more flexibility should any future functions want …
> Refactored NewMachine and Start functions

- Makefile
Signed-off-by: Mathis Joffre <mariusjoffre@gmail.com>
*Issue #, if available:* #364
Sorry for multiple PR opening I had some troubles with my branches and squashing. This the final PR for this issue.
> Pin version of ltag for go <= v1.15 compatibility

- CHANGELOG.md
- version.go
Signed-off-by: Yasin Turan <turyasin@amazon.com>
> Release v1.0.0

- Makefile
Signed-off-by: David Son <son.david.b@gmail.com>
Firecracker's `build_rootfs` command now supports [specifying a mount directory](https://github.com/firecracker-microvm/firecracker/pull/3086) via the `-m` flag. This should (hopefully) make the pipeline a little less flaky if this is indeed the reason for the command to seemingly randomly fail.
It's worth nothing that if this is the real issue (which it seems to not be), this means we can remove the pipeline concurrency group. I think I shared some info with the team as to what behaviors are shown before the loop device setup fails (specifically, when creating the working directory in the first pipeline step, the ones that fail to setup the loop device seem to have a different setup …
> Added mount directory to build_rootfs command

- benchmark_test.go
- examples/cmd/snapshotting/example_demo.go
- internal/cpu_template.go
- internal/cpu_template_test.go
- machine_test.go
Signed-off-by: Vaishnavi Vejella <vvejella@amazon.com>
*Issue:* While testing **AMD** instance against the Firecracker Go SDK, the BuildKite's pipeline tests are getting failed due to CPUTemplate which is not supported by non-intel instances.
*Description of changes:* Added two files [cpu_template.go](https://github.com/firecracker-microvm/firecracker-containerd/blob/main/internal/cpu_template.go 
), [cpu_template_test.go ](https://github.com/firecracker-microvm/firecracker-containerd/blob/main/internal/cpu_template_test.go)by taking reference from firecracker-containerd to determine that CPU template is only supported by Intel. 
> Removing CPU template from Config for non-intel instance

- .github/workflows/go.yml
n/a
Updating GHA OS matrix to use the latest Ubuntu image available.
* Removed 18.04 marked for deprecation
* Updated 20.04 to 22.04 which both use the same Linux kernel so no reason to have both.
> Update GHA runner images

- .github/workflows/go.yml
*Issue #, if available:* #463
To get rid of the actions warnings because of Node 12 deprecations this will bump the actions to use Node 16 by default. This closes #463. 
I tested it locally with running [act](https://github.com/nektos/act). If there is another way to do so please let me know.
> Chore: Bump GH actions versions

- machine_test.go
Signed-off-by: Vaishnavi Vejella <vvejella@amazon.com>
*Issue #467:*
**TestJailerMicroVMExecution** is failed to start VMM and Firecracker was not able to create an API socket due to CgroupsVersion field on the JailerConfig is not specified, thus the default is using v1 with the jailer binary.
Modified the Jailer Config by specifying cgroups as v2 in TestJailerMicroVMExecution to` CgroupVersion: "2"`
> Specify Cgroups versions for JailerConfig

- .buildkite/pipeline.yml
- examples/cmd/snapshotting/Makefile
We are using sudo too much. While there are operations that only root can do (chown, mount, ...), go and make don't need root.
> Reduce sudo

- .hack/go.mod
- .hack/go.sum
- Makefile
- machine.go
- network_test.go
Signed-off-by: Vaishnavi Vejella <vvejella@amazon.com>
*Issue:*
While trying to perform ARM integration test against firecracker-go-sdk, found that **SendCtrlAltDel** is not supported on aarch64 and **TestNetworkMachineCNIWithConfFile** test is failing because **testPing** is not supported when we are running the test on multiple VM's.
If the architecture is **ARM64**, we are not able to send **SendCtrlAltDel** (API) on aarch64, so stopping the machine using `StopVMM()` and also skipping the test by not passing the VM's then **TestNetworkMachineCNIWithConfFile** will get passed.
> Adding requirements to support ARM instance

- .buildkite/pipeline.yml
- Makefile
Firecracker's main branch cannot be built, probably due to https://github.com/firecracker-microvm/firecracker/pull/3361.
However this should not prevent running tests against Firecracker's released version we already have in the BuildKite hosts.
> Run tests against Firecracker's released version even test-images fails

- .buildkite/pipeline.yml
- Makefile
- examples/cmd/snapshotting/Makefile
- examples/cmd/snapshotting/README.md
- examples/cmd/snapshotting/example_demo.go
#418 
The main branch is failing due to hardcoded rootfs name as the name changed with upstream firecracker moving from bionic to jammy.  Also devtool used to build rootfs is unstable. 
```
cp: cannot stat 'build/firecracker/build/rootfs/bionic.rootfs.ext4': No such file or directory
```
1. Not specify the ubuntu version name but using regex to match it. The approach is safe since we will only have one rootfs built at a time.
2. Use prebuilt rootfs and ssh key from S3 instead of building from devtool on fly which seems pretty unstable.
3.  Update readme of snapshotting example to reflect current status. 
4.  Minor update for the snapshotting example code to clean up generated files. 
By submitting this pull request, I confirm that my …
> Fix CI build by using pre-built rootfs image

- benchmark_test.go
- examples/cmd/snapshotting/example_demo.go
- jailer.go
- machine_test.go
- network_test.go
- vsock/dial.go
The package has been deprecated since 1.16.
#440 
firecracker-go-sdk has dropped Go 1.14 and 1.15
Signed-off-by: NanamiNakano <thynanami@gmail.com>
> chore: Replaced deprecated methods in ioutil using io and os packages

- .github/dependabot.yml
N/A
GitHub Actions workflows are showing deprecation warnings which can be resolved by dependabot automation.
This change adds GitHub Actions packages update automation.
> Add dependabot configuration for GitHub Actions packages

- machine_test.go
This reverts commit d9c024234199e3cb155f5bc97a59a7ce5fbba20f.
*Issue #, if available:* The above PR requires more work since latest Firecracker logging configuration has been updated and it no longer produces similar results as v1.4.1. Reverting the above change, since we need to redo the test entirely
> Revert "fix TestLogAndMetrics"

- jailer.go
*Issue #, if available:* https://github.com/firecracker-microvm/firecracker-go-sdk/issues/534
*Description of changes:* In upgrading Firecracker, I noticed a handful of new log lines regarding invocations of the Firecracker API. I've traced them down to [logging the API call](https://github.com/firecracker-microvm/firecracker/blob/e641bfb584a8a029c9585d96da16d6195354fca5/src/firecracker/src/api_server/parsed_request.rs#L69), and [a series of successful request messages](https://github.com/search?q=repo%3Afirecracker-microvm%2Ffirecracker%20%22The%20request%20was%20executed%20successfully%22&type=code). To reduce the amount of log output from Firecracker, I tried adjusting the log level to `Warning`, but it had no effect as the `jailer` and the SDK do not seem to respect the setting if no …
> Pass `--level` through `jailer` if set

- jailer.go
This reverts commit fe672947d6eeda2d2c99ff1379a766cbc25e0fee.
Passing `--log-level` without passing `log-path` [is not supported](https://github.com/firecracker-microvm/firecracker/blob/v1.4.1/src/firecracker/src/main.rs#L182-L186) in firecracker v1.4.1. The above PR breaks that behavior resulting in CI failures.  This behavior has been changed since firecracker v1.5.0, so we should be able to make the change once we update this SDK to support v1.5.0 api. But for now the behavior should remain consistent with v1.4.1 api. 
Adding a separate issue #580 580 to track the addition of this change once we upgrade go-sdk to support firecracker v1.5.0 
@gudmundur @austinvazquez 
By submitting this pull request, I confirm that my contribution is …
> Revert "Pass firecracker log level through jailer"

- .github/workflows/go.yml
- go.mod
- go.sum
*Issue #, if available:* failing builds on dependabot PR https://github.com/firecracker-microvm/firecracker-go-sdk/pull/578
Updates the minimum go version since containernetworking/cni now requires go 1.21
> ci: upgrade min go version so that newer versions of containernetworking/cni can build

- machine_test.go
N/A
Firecracker mainline is now on v1.10.0-dev, but our version regex only allowed a single digit for each part of the version. This allows 1+ digits for each part.
> Fix get firecracker version test

- README.md
Description of changes:
The Slack invite link seems to be invalid. I changed it to the one that is shown at https://firecracker-microvm.github.io/
> Fix Slack invite link

- handlers.go
- opts.go
Closes #627
As LoadSnapshot requires only a subset of the default handlers, it was implemented by assigning the FcInit handlers to a smaller list of handlers. However, this meant that it would overwrite the FcInit handlers given by the jailer. This PR fixes this behavior by just removing the unnecessary handlers, instead of overwriting them entirely.
> Do not overwrite handlers in LoadSnapshot

- .github/workflows/go.yml
- README.md
- doc.go
- examples/cmd/snapshotting/go.mod
- go.mod
This change updates the minimum required Go version to Go 1.23 to unblock dependabot PRs.
> Bump Go min version to Go 1.23

- opts.go
> Fix BuildKite CI for kernel image path errors when loading snapshots
